<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="com" nsURI="http:///com.ecore" nsPrefix="com">
  <eSubpackages name="bodkink" nsURI="http:///com/bodkink.ecore" nsPrefix="com.bodkink">
    <eSubpackages name="hotel" nsURI="http:///com/bodkink/hotel.ecore" nsPrefix="com.bodkink.hotel">
      <eSubpackages name="presentation" nsURI="http:///com/bodkink/hotel/presentation.ecore"
          nsPrefix="com.bodkink.hotel.presentation"/>
      <eSubpackages name="business" nsURI="http:///com/bodkink/hotel/business.ecore"
          nsPrefix="com.bodkink.hotel.business">
        <eClassifiers xsi:type="ecore:EClass" name="IGuestManagement" abstract="true"
            interface="true">
          <eOperations name="checkOut" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
          </eOperations>
          <eOperations name="checkIn" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="roomReservation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservation"/>
            <eParameters name="guests" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Guest"/>
          </eOperations>
          <eOperations name="checkOut" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="roomReservation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservation"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IRoomExtraManagement" abstract="true"
            interface="true">
          <eOperations name="createRoomExtra" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomExtra">
            <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="editRoomExtra" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomExtra">
            <eParameters name="roomExtra" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomExtra"/>
          </eOperations>
          <eOperations name="listRoomExtras" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/RoomExtra"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IRoomManagement" abstract="true"
            interface="true">
          <eOperations name="create" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Room">
            <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eParameters name="allowedGuest" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eParameters name="size" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
            <eParameters name="nightPrice" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
            <eParameters name="picUrls" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eParameters name="classification" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Classification"/>
            <eParameters name="bedTypes" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
            <eParameters name="roomExtras" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/RoomExtra"/>
          </eOperations>
          <eOperations name="listRooms" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Room"/>
          <eOperations name="editRoom" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Room">
            <eParameters name="room" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Room"/>
          </eOperations>
          <eOperations name="disableRoom" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="findRoom" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Room">
            <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IRoomReservationManagement" abstract="true"
            interface="true">
          <eOperations name="listRoomReservations" ordered="false" upperBound="-1"
              eType="#//bodkink/hotel/business/model/RoomReservation"/>
          <eOperations name="listRoomReservations" ordered="false" upperBound="-1"
              eType="#//bodkink/hotel/business/model/RoomReservation">
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
          </eOperations>
          <eOperations name="listRoomReservations" ordered="false" upperBound="-1"
              eType="#//bodkink/hotel/business/model/RoomReservation">
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
          </eOperations>
          <eOperations name="create" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservation">
            <eParameters name="room" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Room"/>
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="roomReservationType" ordered="false" lowerBound="1"
                eType="#//bodkink/hotel/business/model/RoomReservationType"/>
          </eOperations>
          <eOperations name="findRoomReservation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservation">
            <eParameters name="roomReservationId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="cancelRoomReservation" ordered="false" lowerBound="1"
              eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="roomReservationId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IServiceManagement" abstract="true"
            interface="true">
          <eOperations name="createService" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Service">
            <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="width" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
          </eOperations>
          <eOperations name="editService" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Service">
            <eParameters name="service" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Service"/>
          </eOperations>
          <eOperations name="listServices" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Service"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IBedTypeManagement" abstract="true"
            interface="true">
          <eOperations name="createBedType" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BedType">
            <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="length" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eParameters name="width" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eParameters name="noOfSleepingSpots" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eOperations>
          <eOperations name="editBedType" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BedType">
            <eParameters name="bedType" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BedType"/>
          </eOperations>
          <eOperations name="listBedTypes" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/BedType"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IBillableItemManagement" abstract="true"
            interface="true">
          <eOperations name="createBillableItem" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BillableItem">
            <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
          </eOperations>
          <eOperations name="editBillableItem" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BillableItem">
            <eParameters name="billableItem" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BillableItem"/>
          </eOperations>
          <eOperations name="listBillableItems" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/BillableItem"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IBillingManagement" abstract="true"
            interface="true">
          <eOperations name="createRoomBill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomBill">
            <eParameters name="roomReservation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservation"/>
          </eOperations>
          <eOperations name="createBookingBill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BookingBill">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
            <eParameters name="bookingBillType" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BookingBillType"/>
          </eOperations>
          <eOperations name="addBillableItem" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="roomBill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomBill"/>
            <eParameters name="item" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BillableItem"/>
            <eParameters name="quantity" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
          </eOperations>
          <eOperations name="findRoomBill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomBill">
            <eParameters name="roomReservationId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="makePayment" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="bill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Bill"/>
            <eParameters name="cardInformation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CardInformation"/>
          </eOperations>
          <eOperations name="generateReceipts" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Receipt">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
          </eOperations>
          <eOperations name="generateReceipt" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Receipt">
            <eParameters name="bill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Bill"/>
          </eOperations>
          <eOperations name="makePayment" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="bill" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Bill"/>
            <eParameters name="customer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
          </eOperations>
          <eOperations name="makePayment" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IBookingManagement" abstract="true"
            interface="true">
          <eOperations name="create" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking">
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="rooms" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Room"/>
            <eParameters name="services" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Service"/>
            <eParameters name="numberOfGuests" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eParameters name="customer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
          </eOperations>
          <eOperations name="listBookings" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Booking"/>
          <eOperations name="findBooking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking">
            <eParameters name="bookingId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="listBookings" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Booking">
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
          </eOperations>
          <eOperations name="listAvailableRooms" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Room">
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="endDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
          </eOperations>
          <eOperations name="cancelBooking" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
          </eOperations>
          <eOperations name="getBookingStatus" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/ReservationStatusEnum">
            <eParameters name="bookingId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="confirmAndPay" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Receipt">
            <eParameters name="booking" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Booking"/>
            <eParameters name="cardInformation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CardInformation"/>
          </eOperations>
          <eOperations name="searchRoom" ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/Room">
            <eParameters name="numberOfGuests" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
            <eParameters name="numberOfRooms" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
            <eParameters name="start" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eParameters name="end" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ICustomerManagement" abstract="true"
            interface="true">
          <eOperations name="createCustomer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer">
            <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="birthYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eParameters name="cardInformation" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CardInformation"/>
          </eOperations>
          <eOperations name="editCustomer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer">
            <eParameters name="customer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
          </eOperations>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IAccountManagement" abstract="true"
            interface="true">
          <eOperations name="createCustomerAccount" ordered="false" lowerBound="1"
              eType="#//bodkink/hotel/business/model/CustomerUserAccount">
            <eParameters name="username" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="customer" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
          </eOperations>
          <eOperations name="createEmployeeAccount" ordered="false" lowerBound="1"
              eType="#//bodkink/hotel/business/model/UserAccount">
            <eParameters name="username" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="userGroup" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/UserGroupEnum"/>
          </eOperations>
          <eOperations name="editUserAccount" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/UserAccount">
            <eParameters name="userAccount" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/UserAccount"/>
          </eOperations>
          <eOperations name="login" ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CustomerUserAccount">
            <eParameters name="username" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="isLoggedIn" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        </eClassifiers>
        <eSubpackages name="model" nsURI="http:///com/bodkink/hotel/business/model.ecore"
            nsPrefix="com.bodkink.hotel.business.model">
          <eClassifiers xsi:type="ecore:EClass" name="Address">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressLine1" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressLine2" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="zipCode" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BedType">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="places" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Bill" abstract="true">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="billStatusEnum"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BillStatusEnum"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="cardInformation"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CardInformation"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="BillStatusEnum">
            <eLiterals name="PAID"/>
            <eLiterals name="NOT_PAID" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CardInformation">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardNumber" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardHolderName"
                ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate"
                ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="address" ordered="false"
                lowerBound="1" eType="#//bodkink/hotel/business/model/Address"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BillableItem">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Booking">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//Real"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="customer" ordered="false"
                lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="roomReservation"
                ordered="false" upperBound="-1" eType="#//bodkink/hotel/business/model/RoomReservation"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/Service"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="bookingBill" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/BookingBill"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//bodkink/hotel/business/model/Person">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" ordered="false"
                upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="cardInformation"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/CardInformation"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Person">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="Surname" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="BirthYear" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="RoomReservation">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="guest" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/Guest"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomReservationType"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/RoomReservationType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false"
                lowerBound="1" eType="#//bodkink/hotel/business/model/Room"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="roomBill" ordered="false"
                lowerBound="1" eType="#//bodkink/hotel/business/model/RoomBill"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="reservationStatusEnum"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/ReservationStatusEnum"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Guest" eSuperTypes="#//bodkink/hotel/business/model/Person"/>
          <eClassifiers xsi:type="ecore:EEnum" name="RoomReservationType">
            <eLiterals name="BOOKING"/>
            <eLiterals name="IN_SERVICE" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Room">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowedGuests"
                ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="nightPrice" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="pictures" ordered="false"
                upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="classification"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/Classification"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="bedType" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/BedType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="roomExtra" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/RoomExtra"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Classification">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="RoomExtra">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="RoomBill" eSuperTypes="#//bodkink/hotel/business/model/Bill">
            <eStructuralFeatures xsi:type="ecore:EReference" name="billableItem" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/BillableItem"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="ReservationStatusEnum">
            <eLiterals name="CHECKED_IN"/>
            <eLiterals name="CHECKED_OUT" value="1"/>
            <eLiterals name="RESERVED" value="2"/>
            <eLiterals name="CANCELED" value="3"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Service">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BookingBill" eSuperTypes="#//bodkink/hotel/business/model/Bill">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="bookingBillType"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/BookingBillType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="BookingBillType">
            <eLiterals name="RESERVATION_FEE"/>
            <eLiterals name="FINALIZE" value="1"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="RoomExtraTemplate">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="roomExtra" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/RoomExtra"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Receipt">
            <eStructuralFeatures xsi:type="ecore:EReference" name="receiptItem" ordered="false"
                upperBound="-1" eType="#//bodkink/hotel/business/model/ReceiptItem"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ReceiptItem"/>
          <eClassifiers xsi:type="ecore:EClass" name="UserAccount">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
                lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="UserGroupEnum">
            <eLiterals name="ADMIN"/>
            <eLiterals name="MANAGER" value="1"/>
            <eLiterals name="CLERK" value="2"/>
            <eLiterals name="CUSTOMER" value="3"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CustomerUserAccount" eSuperTypes="#//bodkink/hotel/business/model/UserAccount">
            <eStructuralFeatures xsi:type="ecore:EReference" name="customer" ordered="false"
                lowerBound="1" eType="#//bodkink/hotel/business/model/Customer"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="userGroupEnum"
                ordered="false" lowerBound="1" eType="#//bodkink/hotel/business/model/UserGroupEnum"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="logic" nsURI="http:///com/bodkink/hotel/business/logic.ecore"
            nsPrefix="com.bodkink.hotel.business.logic">
          <eClassifiers xsi:type="ecore:EClass" name="GuestManagement" eSuperTypes="#//bodkink/hotel/business/IGuestManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="RoomExtraManagement" eSuperTypes="#//bodkink/hotel/business/IRoomExtraManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="RoomManagement" eSuperTypes="#//bodkink/hotel/business/IRoomManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="RoomReservationManagement" eSuperTypes="#//bodkink/hotel/business/IRoomReservationManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="ServiceManagement" eSuperTypes="#//bodkink/hotel/business/IServiceManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="BedTypeManagement" eSuperTypes="#//bodkink/hotel/business/IBedTypeManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="BillableItemManagement" eSuperTypes="#//bodkink/hotel/business/IBillableItemManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="BillingManagement" eSuperTypes="#//bodkink/hotel/business/IBillingManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="BookingManagement" eSuperTypes="#//bodkink/hotel/business/IBookingManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="CustomerManagement" eSuperTypes="#//bodkink/hotel/business/ICustomerManagement"/>
          <eClassifiers xsi:type="ecore:EClass" name="AccountManagement" eSuperTypes="#//bodkink/hotel/business/IAccountManagement"/>
        </eSubpackages>
      </eSubpackages>
      <eSubpackages name="persistence" nsURI="http:///com/bodkink/hotel/persistence.ecore"
          nsPrefix="com.bodkink.hotel.persistence"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
